// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtbXPY_1dGAAqWjbVOI7oR2YR-l475CHs',
    appId: '1:169187133997:web:a431f218b532a433da06a4',
    messagingSenderId: '169187133997',
    projectId: 'yelitalk',
    authDomain: 'yelitalk.firebaseapp.com',
    storageBucket: 'yelitalk.firebasestorage.app',
    measurementId: 'G-E8MSZYX9V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVb3dEbQuQ4L8DUwbgQWeOaAU8y9E4PIg',
    appId: '1:169187133997:android:98e21b2f146bec12da06a4',
    messagingSenderId: '169187133997',
    projectId: 'yelitalk',
    storageBucket: 'yelitalk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8POPiDCSSDPV88sHr29qx5rnNtoB6cTA',
    appId: '1:169187133997:ios:c40b21ab34db4f3fda06a4',
    messagingSenderId: '169187133997',
    projectId: 'yelitalk',
    storageBucket: 'yelitalk.firebasestorage.app',
    iosBundleId: 'com.example.YeliTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8POPiDCSSDPV88sHr29qx5rnNtoB6cTA',
    appId: '1:169187133997:ios:c40b21ab34db4f3fda06a4',
    messagingSenderId: '169187133997',
    projectId: 'yelitalk',
    storageBucket: 'yelitalk.firebasestorage.app',
    iosBundleId: 'com.example.YeliTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtbXPY_1dGAAqWjbVOI7oR2YR-l475CHs',
    appId: '1:169187133997:web:86d40adcc51e1e93da06a4',
    messagingSenderId: '169187133997',
    projectId: 'yelitalk',
    authDomain: 'yelitalk.firebaseapp.com',
    storageBucket: 'yelitalk.firebasestorage.app',
    measurementId: 'G-DN9ME3NHYN',
  );
}
